### ISSUE TITLE
updates for newly published GDB

### ISSUE THREAD

**Issue by debboutr** [ACWI-SSWD/nhdplus-pg-prep#7]
it seems like there are some changes to the format of the gdb for what is published here [https://www.epa.gov/waterdata/nhdplus-national-data](https://www.epa.gov/waterdata/nhdplus-national-data)

I was hoping to get this up in a docker container real quick, but don't have the ability use ESRI at the moment to see the GDB data. I tried to just rename the newly published GDB to the name you use in the `config_commands.sh` script but am getting errors at every `ogr2ogr` command. 

Would it be worth me trying to work out the details with what the EPA has published now and make a PR or have you abandoned V21 and moved onto the high-res? I would imagine that this is still useful, but I don't want to kill too much time if it's not going to do anybody any good. OR maybe I'm missing something completely in which case I'd love to hear what the fix might be. Thanks!

here is the error that I'm getting....
```
Insert Catchments into Database as Catchment.
ERROR 1: ERROR:  column s.consrc does not exist
LINE 1: ...nrelid = c.oid AND a.attnum = ANY (s.conkey) AND (s.consrc L...
                                                             ^
HINT:  Perhaps you meant to reference the column "s.conkey" or the column "s.conbin".

ERROR 1: ERROR:  column s.consrc does not exist
LINE 1: ...nrelid = c.oid AND a.attnum = ANY (s.conkey) AND (s.consrc L...

```
this seems strange cause the columns in Catchments look right...
```
root@9e324acbd165:/home/nhdplus-pg-prep# ogrinfo ./NHDPlusNationalData/NHDPlusV21_National_Seamless.gdb Catchment -so
INFO: Open of `./NHDPlusNationalData/NHDPlusV21_National_Seamless.gdb'
      using driver `OpenFileGDB' successful.

Layer name: Catchment
Geometry: Multi Polygon
Feature Count: 2647454
Extent: (-124.733655, 24.630445) - (-66.949542, 52.880043)
Layer SRS WKT:
GEOGCS["NAD83",
    DATUM["North_American_Datum_1983",
        SPHEROID["GRS 1980",6378137,298.257222101,
            AUTHORITY["EPSG","7019"]],
        TOWGS84[0,0,0,0,0,0,0],
        AUTHORITY["EPSG","6269"]],
    PRIMEM["Greenwich",0,
        AUTHORITY["EPSG","8901"]],
    UNIT["degree",0.0174532925199433,
        AUTHORITY["EPSG","9122"]],
    AUTHORITY["EPSG","4269"]]
FID Column = OBJECTID
Geometry Column NOT NULL = Shape
GRIDCODE: Integer (0.0)
FEATUREID: Integer (0.0)
SOURCEFC: String (20.0)
AreaSqKM: Real (0.0)
Shape_Length: Real (0.0)
Shape_Area: Real (0.0)
```

**Comment by debboutr** [comment]
I've used an older version of postgres and the issue is fixed. The problem was that I was on postgres v. 12, I went back to 10 and the script runs! here is the issue I found that explains the [problem](https://gis.stackexchange.com/questions/342246/ogr2ogr-from-file-to-postgresql-12-table-fails)

**Comment by dblodgett-usgs** [comment]
Wow, glad you got this working!! I haven't looked at this for a long time, kind of surprised its not more stale. Thanks for finding the fix!
